f = open("doc.txt","w")
f.write("mariam\nmohamed\nabdelhamid\nmohamed")
f.close()
f = open(r"doc.txt",'r')
file = f.read()
print(file)
with open(r"doc.txt",'r') as f:
    lines = len(f.readlines())
    print("no. of lines:" ,lines)
    print("no. of words:" ,len(file.split()))
f.close()
